export const allProjects = [
  {
    img: "dummy-image.webp",
    title: "The Bias Variance Tradeoff",
    description:
      "Built a robust predictive modeling system using Python and Scikit-Learn, orchestrated with Apache Airflow for automated data ingestion and cleaning.",
    tools: [
      "Python",
      "Scikit-Learn",
      "Apache Airflow",
      "n8n",
      "LangSmith",
      "MLflow",
      "AWS",
    ],
    image: null,
    github: "https://github.com",
  },
  {
    img: "dummy-image.webp",
    title: "The Bias Variance Tradeoff",
    description:
      "Built a robust predictive modeling system using Python and Scikit-Learn, orchestrated with Apache Airflow for automated data ingestion and cleaning.",
    tools: [
      "Python",
      "Scikit-Learn",
      "Apache Airflow",
      "n8n",
      "LangSmith",
      "MLflow",
      "AWS",
    ],
    image: null,
    github: "https://github.com",
  },
  {
    img: "dummy-image.webp",
    title: "The Bias Variance Tradeoff",
    description:
      "Built a robust predictive modeling system using Python and Scikit-Learn, orchestrated with Apache Airflow for automated data ingestion and cleaning.",
    tools: [
      "Python",
      "Scikit-Learn",
      "Apache Airflow",
      "n8n",
      "LangSmith",
      "MLflow",
      "AWS",
    ],
    image: null,
    github: "https://github.com",
  },
  {
    img: "dummy-image.webp",
    title: "The Bias Variance Tradeoff",
    description:
      "Built a robust predictive modeling system using Python and Scikit-Learn, orchestrated with Apache Airflow for automated data ingestion and cleaning.",
    tools: [
      "Python",
      "Scikit-Learn",
      "Apache Airflow",
      "n8n",
      "LangSmith",
      "MLflow",
      "AWS",
    ],
    image: null,
    github: "https://github.com",
  },
  {
    img: "dummy-image.webp",
    title: "The Bias Variance Tradeoff",
    description:
      "Built a robust predictive modeling system using Python and Scikit-Learn, orchestrated with Apache Airflow for automated data ingestion and cleaning.",
    tools: [
      "Python",
      "Scikit-Learn",
      "Apache Airflow",
      "n8n",
      "LangSmith",
      "MLflow",
      "AWS",
    ],
    image: null,
    github: "https://github.com",
  },
  {
    img: "dummy-image.webp",
    title: "The Bias Variance Tradeoff",
    description:
      "Built a robust predictive modeling system using Python and Scikit-Learn, orchestrated with Apache Airflow for automated data ingestion and cleaning.",
    tools: [
      "Python",
      "Scikit-Learn",
      "Apache Airflow",
      "n8n",
      "LangSmith",
      "MLflow",
      "AWS",
    ],
    image: null,
    github: "https://github.com",
  },
  {
    img: "dummy-image.webp",
    title: "The Bias Variance Tradeoff",
    description:
      "Built a robust predictive modeling system using Python and Scikit-Learn, orchestrated with Apache Airflow for automated data ingestion and cleaning.",
    tools: [
      "Python",
      "Scikit-Learn",
      "Apache Airflow",
      "n8n",
      "LangSmith",
      "MLflow",
      "AWS",
    ],
    image: null,
    github: "https://github.com",
  },
  {
    img: "dummy-image.webp",
    title: "The Bias Variance Tradeoff",
    description:
      "Built a robust predictive modeling system using Python and Scikit-Learn, orchestrated with Apache Airflow for automated data ingestion and cleaning.",
    tools: [
      "Python",
      "Scikit-Learn",
      "Apache Airflow",
      "n8n",
      "LangSmith",
      "MLflow",
      "AWS",
    ],
    image: null,
    github: "https://github.com",
  },
  {
    img: "dummy-image.webp",
    title: "The Bias Variance Tradeoff",
    description:
      "Built a robust predictive modeling system using Python and Scikit-Learn, orchestrated with Apache Airflow for automated data ingestion and cleaning.",
    tools: [
      "Python",
      "Scikit-Learn",
      "Apache Airflow",
      "n8n",
      "LangSmith",
      "MLflow",
      "AWS",
    ],
    image: null,
    github: "https://github.com",
  },
];
